---
title: The Syntheticist Papers, I. Proceedings of the Synthetic Summit 2025
description: A catalogue featuring essays and videos on synthetic statecraft.
markdown: kramdown
theme: minima
baseurl: "/The-Syntheticist-Papers"